
# Site settings
title: Yanzhao Shi
name: Yanzhao Shi
subtitle:  Student
email: s202274029@emails.bjut.edu.cn
description: >
   Student
baseurl: ""
url: "https://YanzhaoShi.github.io/"
github_username:  YanzhaoShi
disqus_baseurl: "https://YanzhaoShi.github.io/"
disqus_shortname: https-YanzhaoShi-github-io
permalink: :title
# google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yanzhao Shi"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/YanzhaoShi
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Yanzhao Shi
    url: https://scholar.google.com/citations?user=pRARRDQAAAAJ&hl=zh-CN
    desc: Connect with me on LinkedIn
    share: true
